/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MotoboyRouteImport } from './routes/motoboy'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminMotoboysRouteImport } from './routes/admin.motoboys'
import { Route as AdminEntregasRouteImport } from './routes/admin.entregas'
import { Route as AdminConfigRouteImport } from './routes/admin.config'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoboyRoute = MotoboyRouteImport.update({
  id: '/motoboy',
  path: '/motoboy',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoboysRoute = AdminMotoboysRouteImport.update({
  id: '/admin/motoboys',
  path: '/admin/motoboys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/admin/entregas',
  path: '/admin/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/motoboy': typeof MotoboyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/motoboys': typeof AdminMotoboysRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/motoboy': typeof MotoboyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/motoboys': typeof AdminMotoboysRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/motoboy': typeof MotoboyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/motoboys': typeof AdminMotoboysRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/motoboy'
    | '/sitemap.xml'
    | '/admin/config'
    | '/admin/entregas'
    | '/admin/motoboys'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/motoboy'
    | '/sitemap.xml'
    | '/admin/config'
    | '/admin/entregas'
    | '/admin/motoboys'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$numero'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/motoboy'
    | '/sitemap.xml'
    | '/admin/config'
    | '/admin/entregas'
    | '/admin/motoboys'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MotoboyRoute: typeof MotoboyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminMotoboysRoute: typeof AdminMotoboysRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoboy': {
      id: '/motoboy'
      path: '/motoboy'
      fullPath: '/motoboy'
      preLoaderRoute: typeof MotoboyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoboys': {
      id: '/admin/motoboys'
      path: '/admin/motoboys'
      fullPath: '/admin/motoboys'
      preLoaderRoute: typeof AdminMotoboysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/admin/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  MinhaContaRoute: MinhaContaRoute,
  MotoboyRoute: MotoboyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminMotoboysRoute: AdminMotoboysRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
